#!/bin/bash
echo -e "\033[1;36mУстанавливаю node.js из исходников, можно попить чайку... литра 2 :-)\033[0m"
cd ~
wget -q https://nodejs.org/dist/index.tab
ver=$(grep -E -o "v([0-9]+\\.[0-9]+\\.[0-9]+)" ./index.tab | sed -n '1,1p')
echo -e "\033[1;36mпоследняя версия node.js \033[0;31m"$ver"\033[0m"
wget -q https://nodejs.org/dist/$ver/node-$ver.tar.gz 
tar -xf node-$ver.tar.gz 
rm node-$ver.tar.gz 
cd node-$ver
echo -n -e "\033[1;36mустановка продлиться продолжительное время (возможно 2-3 часа), подождите завершения...\033[0m"
./configure
make -s
make -s install
echo -e "\033[1;32m установлено\033[0m"
