#!/bin/bash
wget https://github.com/blynkkk/blynk-server/releases
st1="https://github.com"$(grep -A 1 -o "/blynkkk/blynk-server/releases/download/\(.*\)-java8.jar" ./releases -m 1)
st2=$(grep -A 1 -o "server-\(.*\)-java8.jar" ./releases -m 1)
echo $st1
mkdir /home/pi/blynk
wget -P /home/pi/ $st1
chmod 777 /home/pi/$st2
