#!/bin/bash

mysql -u root << EOF
SELECT CONCAT('ALTER TABLE ',table_schema,'.',table_name,' ENGINE=MyISAM;')
FROM information_schema.tables
WHERE 1=1
  AND engine = 'InnoDB'
  AND table_schema NOT IN ('mysql', 'performance_schema');
EOF

echo "innodb=OFF" | tee -a /etc/mysql/mariadb.conf.d/50-server.cnf
echo "default-storage-engine = MyISAM" | tee -a /etc/mysql/mariadb.conf.d/50-server.cnf


service mysqld stop \
  && rm -f /tmp/mysql/ibdata1 \
  && rm -f /tmp/mysql/ib_logfile* \
  && rm -f /var/lib/mysql/ibdata1 \
  && rm -f /var/lib/mysql/ib_logfile* \  
  && service mysqld start
