#!/bin/bash

#конвертируем все таблицы кроме системных из InnoDB в MyISAM
mysql -u root << EOF
SELECT CONCAT('ALTER TABLE ',table_schema,'.',table_name,' ENGINE=MyISAM;')
FROM information_schema.tables
WHERE 1=1
  AND engine = 'InnoDB'
  AND table_schema NOT IN ('mysql', 'performance_schema');
EOF

#добавляем в конфиг mysql выключение использования InnoDB
#ищем конфиг MySQL
dbconfig=$(grep -iRIl "datadir" /etc/mysql)
#добавляем в конфиг InnoDB выключить и по умолчанию юзать MyISAM
echo "innodb=OFF" | tee -a $dbconfig
echo "default-storage-engine = MyISAM" | tee -a $dbconfig

#удаляем все файлы относящиеся к InnoDB
service mysql stop
rm -f /tmp/mysql/ibdata1
rm -f /tmp/mysql/ib_logfile*
rm -f /var/lib/mysql/ibdata1
rm -f /var/lib/mysql/ib_logfile* 
service mysql start
